# Generated by Django 4.0.5 on 2022-12-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64, null=True)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('topic_file', models.FileField(upload_to='topic_files/')),
                ('grade_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GradeAndSectionList', to='Home.gradeandsection')),
            ],
        ),
    ]
