# Generated by Django 4.0.5 on 2022-12-22 19:02

import Stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=Stories.models.randomGenerator, editable=False, max_length=10)),
                ('story_name', models.CharField(max_length=64, null=True)),
                ('story_description', models.TextField(blank=True, default=Stories.models.defaultDescription, max_length=300, null=True)),
                ('story_vid', models.FileField(blank=True, upload_to='stories_files/video')),
                ('story_thumbnail', models.ImageField(blank=True, upload_to='stories_files/thumb')),
                ('date_uploadeded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
